travis:
  secure:
    BINSTAR_TOKEN: RHL7a1XSQrEciHGElrnGZ4C3XzpFb+MWfvAaplW6kPJ52yVxV0mfIvgkcyFjWPQV3B9tTrHwQtSl8Q3XH+vccxEpBh9OlDwUcW4FYmuaMOueC8I2CZVJiDPc9OGKzrVV33KCBZftP1KTlCALu1cilc5rsGO76SP/Sy40knQA+dShL2z08f/tBGWNrryMlB2p7tjZoC3lm7iCZPnC9DgQyJlOHe4AFga/K/Sw/uzk2iasjvzrv5CvycV6/ds8Q6DDCu0i2sm1S3P8iAGO0GXbQTKjE2SWJCkUnCnM5lni3vYGn6/wrx4TIsTc1jkIFqMSi+COG3t/m0gHFOwpqLQKri5ZEfannMCrIoDqyQs7YLU0bjMJ05evRJ14/VzCe/uaVlt8v9rSYyiRirfhASMXU8SBmMveNOSvvGX8GN9N5HluqcaAcQ+X9n9V3Up7+V2NWVlT7JI/nAvyW7xiDPJyZ8QEC2iaZVkmYGCA7vWHncVXzamwd4HVcRryN69a/1o8Gel4PGld7U4ZXqaxgvNrOqJH44QvmwrY+67sBPcvi30OigJ4KAkR2ukqsf1g5tA0NaCgQjATLp18dv7BJI2/s6F5hNhokES+pEoEr7Jm7rv3B8uGviSivWqR5Gy2Pu7f20Dmo3fl9a0+T/uk7sIb/g6G5jSyZ5NbVX0U1JN9P14=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
